### ISSUE TITLE
TXSkel.Sign error: number of private keys != length of ToSign array

### ISSUE THREAD

**Issue by adigunhammedolalekan** [blockcypher/gobcy#10]
Hi, Kudos to Blockcypher team.

I got this error while trying to broadcast Transaction on BTC TestNet3 (test3) 
***TXSkel.Sign error: number of private keys != length of ToSign array**, 
The original line of code that produces this error looks like 
 `err := txSkeleton.Sign([]string{privateKey})`,
i tried to get rid of the error by repeating the private key inside .Sign([]string{}) - something like this 

`err := txSkel.Sign([]string(privateKey))
 if err != nil {
    err = txSkel.Sign([]string{privateKey, privateKey}) //try to Sign again by repeating private key entry
   if err != nil {
     //return error message
  }
}`

It worked once, then i started seeing the error again 
***TXSkel.Sign error: number of private keys != length of ToSign array**
Any help will be very much appreciated. Thanks!

**Comment by anielski** [comment]
I see the topic old, does anyone know the solution? I have the same problem ;(

**Comment by dhaileytaha** [comment]
I got how to solve this.

     skel, err := bcy.NewTX(gobcy.TempNewTX(sender, receiver, amount), false)
	    if err != nil {
	    	fmt.Println(err)
	    }
	    //Sign it locally
      //check how many tranxs you need to sign by getting the length of ToSign array in the Skel objec
		fmt.Printf("%+v\n", len(skel.ToSign))
		max := len(skel.ToSign) // this is the number of UTXO you need to sign
		
   		var keys []string
                 //create the array of private keys to sign the UTXOs
   		k:=priv_key
   		  for a := 1; a <= max; a++ {
	    	   keys = append(keys, k)
		}
    	        // pass the private keys array i.e. keys to the skel.Sign function
 	    err = skel.Sign(keys)
	    if err != nil {
	        fmt.Println(err)
	    }
	    //Send TXSkeleton
	    skel, err = bcy.SendTX(skel)
	    if err != nil {
	        fmt.Println(err)
	    }



To understanding this fully you need to know about UTXOs in Bitcoin
So the point is you can spend bitcoin from the UNSPENT bitcoins only.
example. if you receive bitcoins from 4 different addresses you have 4 UNSPENT trnaxs (UTXO), so if you want to spend all of your BTC you need to sign all 4 UTXOs
