### ISSUE TITLE
Broadcasting tx from API call always return error

### ISSUE THREAD

**Issue by altafan** [blockcypher/gobcy#11]
I'm trying to broadcast a signed raw transaction via REST API call to the endpoint:
`https://api.blockcypher.com/v1/bcy/test/txs/push?token=<token>`
passing the tx in the request body:
`{"tx": <signedRawTx>}`
as stated in the documentation.

My problem is that the request always fails with an error like this one: 
`Error validating transaction: Transaction 03f4e5f76bc773bfb6639651ff63668ac6dfc8b75c42855fde16af5407b61592 orphaned, missing reference 2dce14ce7b628641f0305e8511868b4d8758428161bf93b2979f2d9eb00495ce.`

But if I try to broadcast the same transaction from your service (https://live.blockcypher.com/btc-testnet/pushtx/) it doesn't fail.

Am I calling the wrong endpoint?

**Comment by ManFromSiberia** [comment]
@altafan how you resolve this problem?
