### ISSUE TITLE
Error: Script was NOT verified successfully

### ISSUE THREAD

**Issue by boufni95** [blockcypher/gobcy#14]
Hi! I'm trying to create a transaction on bitcoin testnet 
From: 
Public: mvGY7eLArdCv2vAFEQ1UjP1JxpPG7Qk5h6
Private: 93PAkRzFDAgRq8hgdcpAmKri6ApfY1hnbymvEK7WWEppDQVP8vP
To:
Public: ms1MWPgadxuRaaVSVa9i7gobFy6D8HubtJ
On the testnet.

`package main

import (
	"fmt"

	"github.com/blockcypher/gobcy"
)

func main() {
	//note the change to BlockCypher Testnet
	bcy := gobcy.API{"MY-KEY", "btc", "test3"}

	//Post New TXSkeleton
	skel, err := bcy.NewTX(gobcy.TempNewTX("mvGY7eLArdCv2vAFEQ1UjP1JxpPG7Qk5h6", "ms1MWPgadxuRaaVSVa9i7gobFy6D8HubtJ", 400000), false)
	//Sign it locally
	err = skel.Sign([]string{"93PAkRzFDAgRq8hgdcpAmKri6ApfY1hnbymvEK7WWEppDQVP8vP"})
	if err != nil {
		fmt.Println(err)
	}
	//Send TXSkeleton
	skel, err = bcy.SendTX(skel)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Printf("%+v\n", skel)
}
`

From the examples, I think I have to do it like this, but it keeps giving me the error, can you give me some advice?

**Comment by quentinlesceller** [comment]
Closing. Contact us at support@blockcypher.com for support.

**Comment by hoangphuongcs** [comment]
> Hi! I'm trying to create a transaction on bitcoin testnet
> From:
> Public: mvGY7eLArdCv2vAFEQ1UjP1JxpPG7Qk5h6
> Private: 93PAkRzFDAgRq8hgdcpAmKri6ApfY1hnbymvEK7WWEppDQVP8vP
> To:
> Public: ms1MWPgadxuRaaVSVa9i7gobFy6D8HubtJ
> On the testnet.
> 
> `package main
> 
> import (
> "fmt"
> 
> ```
> "github.com/blockcypher/gobcy"
> ```
> 
> )
> 
> func main() {
> //note the change to BlockCypher Testnet
> bcy := gobcy.API{"MY-KEY", "btc", "test3"}
> 
> ```
> //Post New TXSkeleton
> skel, err := bcy.NewTX(gobcy.TempNewTX("mvGY7eLArdCv2vAFEQ1UjP1JxpPG7Qk5h6", "ms1MWPgadxuRaaVSVa9i7gobFy6D8HubtJ", 400000), false)
> //Sign it locally
> err = skel.Sign([]string{"93PAkRzFDAgRq8hgdcpAmKri6ApfY1hnbymvEK7WWEppDQVP8vP"})
> if err != nil {
> 	fmt.Println(err)
> }
> //Send TXSkeleton
> skel, err = bcy.SendTX(skel)
> if err != nil {
> 	fmt.Println(err)
> }
> fmt.Printf("%+v\n", skel)
> ```
> 
> }
> `
> 
> From the examples, I think I have to do it like this, but it keeps giving me the error, can you give me some advice?

hi, can you help me fix this? I also got the same issue :( 
err=> HTTP 400 Bad Request, Message(s): Error validating generated transaction: Error running script for input 0 referencing 0dbf0969dc7657524080520462fe7d6409bcf86e3a024c2a0c81adcc14ff296b at 1: Script was NOT verified successfully.
