### ISSUE TITLE
SendTX(skel) fails 

### ISSUE THREAD

**Issue by myklll** [blockcypher/gobcy#15]
The `SendTX(skel TXSkel) (trans TXSkel, err error)` returns invalid character '<' looking for beginning of value.

The occurred while trying to send a TX with about 150 inputs.

**Comment by quentinlesceller** [comment]
Does it happens regularly or only with large transaction?

**Comment by mychell** [comment]
I have only noticed it with transactions with a lot of Unspents ~180. 
Transactions with lower Unspents work properly.

**Comment by mychell** [comment]
@quentinlesceller any update on this issue?

**Comment by quentinlesceller** [comment]
Hi @mychell, no sorry haven't had time to look at it. I'm guessing there is some kind of buffer limits with the number of inputs. For now I'd advise to limit the number of inputs.

**Comment by myklll** [comment]
Any update on this?

**Comment by myklll** [comment]
Any update on this?

**Comment by quentinlesceller** [comment]
Do you have an example so I can try to debug it ?
