### ISSUE TITLE
Add ETH to readme

### ISSUE THREAD

**Issue by Tosch110** [blockcypher/gobcy#17]
gobcy supports ETH, which should be indicated in the README.

Also an example as there is for BTC as addition would certainly be helpful.

**Comment by Tosch110** [comment]
Is it possible that it is not optimised for ETH usage?

I think this happens on too large numbers (18 decimal places for ETH) 

```cannot unmarshal number 10662261289327332000 into Go struct field Addr.total_received of type int```

**Comment by quentinlesceller** [comment]
Hi, I think this is definitely this https://github.com/blockcypher/gobcy/pull/12 happening.
I'm going to investigate whether we can merge that or not.
