### ISSUE TITLE
Empty TXRefs on BTC with GetAddrFull

### ISSUE THREAD

**Issue by Tosch110** [blockcypher/gobcy#18]
On the open API I have been using the txrefs object to see if a txinput has been spent or not.

Now, on gobcy. GetAddrFull I seem to receive an empty TXRefs structure, even though I expected it to be filled with data (and the open API does show it non-empty)

**Comment by quentinlesceller** [comment]
Do you have some sample code ?

**Comment by Tosch110** [comment]
Yes, actually quite straight forward:

```
blockCypherAPI := gobcy.API{"xxxxxxxxxxxxxxxxxxxxxxx", "btc", "main"}	

blockCypherBtc, err := blockCypherAPI.GetAddrFull("1btcaddress", nil)	
if err != nil {	
  fmt.Println(err)	
}

// fmt.Println(blockCypherBtc) seems to be fine, has the correct balance etc

for _, transaction := range blockCypherBtc.TXRefs {
  //does not reach as TXRefs is empty
}
```

**Comment by quentinlesceller** [comment]
See https://www.blockcypher.com/dev/bitcoin/#address:

TXRefs:
>Optional Array of transaction inputs and outputs for this address. Usually only returned from the standard Address Endpoint.


Hence this works

```golang
package main

import (
	"fmt"

	"github.com/blockcypher/gobcy"
)

func main() {

	blockCypherAPI := gobcy.API{$TOKEN, "btc", "main"}

	blockCypherBtc, err := blockCypherAPI.GetAddr("16dEmsy8uzgPfo5XVZCUEGqZhccT5dqbQ", nil)
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(blockCypherBtc)
	for _, transaction := range blockCypherBtc.TXRefs {
		//does not reach as TXRefs is empty
		fmt.Println(transaction)
	}
}
```

With getAddrFull you get the transaction directly.

When in doubt you can always query the API directly with curl
https://api.blockcypher.com/v1/btc/main/addrs/16dEmsy8uzgPfo5XVZCUEGqZhccT5dqbQ/full?limit=50
https://api.blockcypher.com/v1/btc/main/addrs/16dEmsy8uzgPfo5XVZCUEGqZhccT5dqbQ

Closing.
