### ISSUE TITLE
Add batching support to calls that support it.

### ISSUE THREAD

**Issue by acityinohio** [blockcypher/gobcy#2]
Thanks for the feedback @ThePiachu ! Will add this to the queue.

**Comment by dfkthf125** [comment]
![d9xtpb3f1gizu7bu8z51fpfcdfeaw6rw7m](https://cloud.githubusercontent.com/assets/9912853/15978621/f76048a4-2f67-11e6-9151-7f25cefbc445.png)

**Comment by Dana2109** [comment]
Как?

**Comment by Dana2109** [comment]
Что делать?
Как выбрать?
