### ISSUE TITLE
how to send max amount with gobcy

### ISSUE THREAD

**Issue by hoangphuongcs** [blockcypher/gobcy#20]
Hi guys, I have a temp wallet, I want to send all balance of the temp wallet to a master wallet.
Can you help me with this function, thank you so much!

**Comment by quentinlesceller** [comment]
Just pass -1 as amount (look for "sweep" in the docs)

**Comment by hoangphuongcs** [comment]
> Just pass -1 as amount (look for "sweep" in the docs)

many thanks!
