### ISSUE TITLE
the error: Script was NOT verified successfully

### ISSUE THREAD

**Issue by hoangphuongcs** [blockcypher/gobcy#22]
I send Dash coin to another dash address, but I see an error bellow:
HTTP 400 Bad Request, Message(s): Error validating generated transaction: Error running script for input 0 referencing 55457fcd4607a14ad37d5f61484cdc39c37b5016935eb8c4334ab1385134830c at 0: Script was NOT verified successfully
Can guys help! thank you.

**Comment by quentinlesceller** [comment]
Without any code it's impossible for us to help you.

**Comment by quentinlesceller** [comment]
Also please send an email to support[at]blockcypher[dot]com. This is the proper way to get support.

**Comment by hoangphuongcs** [comment]
> Also please send an email to support[at]blockcypher[dot]com. This is the proper way to get support.

ok, I have sent you via email, please check it, thank you!
