### ISSUE TITLE
gobcy.TempMultiTX built a tx object as NewTX(tx) must be err

### ISSUE THREAD

**Issue by eashme** [blockcypher/gobcy#23]
gobcy.TempMultiTX built a tx object as NewTX(tx) must be err

trans, err := gobcy.TempMultiTX(sender.Address...)
then
API.NewTX(trans, true)
raise ("Error building input: Cannot use P2SH as input without 'script_type' set to 'multisig-n-of-m'")

**Comment by quentinlesceller** [comment]
Can you paste the full code here?
