### ISSUE TITLE
Can not transfer with from address is a BTC segwit address.

### ISSUE THREAD

**Issue by hoangphuongcs** [blockcypher/gobcy#24]
**I can not transfer with **from_address** is a segwit address.**

error: 
HTTP 400 Bad Request, Message(s): Error validating generated transaction: Error running script for input 0 referencing 642fa2f5db306ae7f17d1afc50be5798e3e8ccd8d4a4c6c4b040b45e25defa37 at 0: Script was NOT verified successfully.

I have converted the segwit to legacy address but it still doesn't work for me.
2 addresses with different balances (balance of legacy is 0

the error:
HTTP 400 Bad Request, Message(s): Unable to find a transaction to spend for address 1KC5iLrRUhvsdofmym3kECnjpgQPxy2uTb., Error validating generated transaction: insufficient priority and fee for relay

**can guys help me?**

the code:

```
   wif, err := btcutil.DecodeWIF(secret)
    if err != nil {
        return "", err
    }

    // fromAddress is a segwit address:
    pkHex := hex.EncodeToString(wif.PrivKey.Serialize())
    tx := gobcy.TempNewTX(fromAddress, destination, amount)
    tx.Fees = fee
    skel, err := bs.chain.NewTX(tx, false)

    if err != nil {
        return "", err
    }
    prikHexs := []string{}
    for i := 0; i < len(skel.ToSign); i++ {
        prikHexs = append(prikHexs, pkHex)
    }

    err = skel.Sign(prikHexs)
    if err != nil {
        log.Println(err)
        return "", err
    }

    skel, err = bs.chain.SendTX(skel)
    if err != nil {
        log.Println(err)
        return "", err
    }
    return skel.Trans.Hash, nil
```

**Comment by hoangphuongcs** [comment]
hello!

**Comment by quentinlesceller** [comment]
Answered on support.
