### ISSUE TITLE
how to replace higher fee when the transaction is stuck (pending for a long time)

### ISSUE THREAD

**Issue by hoangphuongcs** [blockcypher/gobcy#25]
how to replace higher fee when the transaction is stuck (pending for a long time)
thank you!

**Comment by quentinlesceller** [comment]
Hi,
 Using the latest master you can specify the sequence and reuse the same and change the gas price. That published transaction will replace the current one.

```Golang
tempTX := gobcy.TempNewTX(FROM, TO, *big.NewInt(VALUE))
tempTX.Inputs[0].Sequence = int(sequence)
tempTX.GasPrice = big.NewInt(0).Mul(gasPrice, big.NewInt(2))
```

Something like that.
